[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "benchmarks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.10"
dependencies = [
  "uvicorn[standard]",
  "fastapi[standard]",
  "fluxqueue",
  "celery",
  "redis",
  "aiosmtplib",
  "sqlalchemy",
  "sqlalchemy-utils",
  "alembic",
  "psycopg2-binary",
  "asyncpg",
]

[project.optional-dependencies]
dev = ["ruff", "matplotlib"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
  "E",   # pycodestyle errors
  "W",   # pycodestyle warnings
  "F",   # pyflakes
  "I",   # isort
  "C",   # flake8-comprehensions
  "B",   # flake8-bugbear
  "UP",  # pyupgrade
  "N",   # pep8-naming
  "SIM", # flake8-simplify
  "RUF", # ruff-specific rules
]
